""" 
Exceptions
In this example, the try block will generate an exception, because x is not defined
"""

try:
    print(x)
except:
  print("An exception occurred")
